fermions:
  description: simulator of a fermionic tweezer hardware. The even wires denote the
    occupations of the spin-up fermions and the odd wires denote the spin-down fermions
  backend_version: 0.0.1
  cold_atom_type: fermion
  conditional: false
  coupling_map: linear
  dynamic_reprate_enabled: false
  gates:
  - name: fhop
    description: hopping of atoms to neighboring tweezers
    coupling_map:
    - [0, 1, 2, 3]
    - [2, 3, 4, 5]
    - [4, 5, 6, 7]
    - [0, 1, 2, 3, 4, 5, 6, 7]
    parameters:
    - j_i
    qasm_def: '{}'
  - name: fint
    description: on-site interaction of atoms of opposite spin state
    coupling_map:
    - [0, 1, 2, 3, 4, 5, 6, 7]
    parameters:
    - u
    qasm_def: '{}'
  - name: fphase
    description: Applying a local phase to tweezers through an external potential
    coupling_map:
    - [0, 1]
    - [2, 3]
    - [4, 5]
    - [6, 7]
    - [0, 1, 2, 3, 4, 5, 6, 7]
    parameters:
    - mu_i
    qasm_def: '{}'
  local: false
  max_experiments: 50
  max_shots: 1000000.0
  memory: true
  n_qubits: 8
  num_species: 2
  open_pulse: false
  simulator: true
  supported_instructions:
  - load
  - measure
  - barrier
  - fhop
  - fint
  - fphase
  wire_order: interleaved


multiqudit:
  description: Setup of a cold atomic gas experiment with qudits.
  atomic_species:
  - na
  backend_version: 0.0.1
  cold_atom_type: spin
  conditional: false
  coupling_map: []
  credits_required: false
  gates:
  - name: rlz
    description: Evolution under the Z gate
    coupling_map: [[0], [1], [2], [3], [4]]
    parameters:
    - delta
    qasm_def: gate rlz(delta) {}
  - name: rlz2
    description: Evolution under Lz2
    coupling_map: [[0], [1], [2], [3], [4]]
    parameters:
    - chi
    qasm_def: gate rlz2(chi) {}
  - name: rlx
    description: Evolution under Lx
    coupling_map: [[0], [1], [2], [3], [4]]
    parameters:
    - omega
    qasm_def: gate rlx(omega) {}
  - name: rlxly
    description: Entanglement between neighboring gates with an xy interaction
    coupling_map:
    - [0,1]
    - [1,2]
    - [2,3]
    - [3,4]
    - [0,1,2,3,4]
    parameters:
    - J
    qasm_def: gate rlylx(J) {}
  local: false
  max_experiments: 500
  max_shots: 1000
  memory: true
  n_qubits: 4
  open_pulse: false
  simulator: true
  supported_instructions:
  - rlx
  - rlz
  - rlz2
  - rlxly
  - barrier
  - measure
  - load
  wire_order: interleaved

singlequdit:
  description: Setup of a cold atomic gas experiment with qudits.
  atomic_species:
  - na
  backend_version: 0.0.2
  cold_atom_type: spin
  conditional: false
  coupling_map: []
  credits_required: false
  gates:
  - name: rlz
    description: Evolution under the Z gate
    coupling_map: []
    parameters:
    - delta
    qasm_def: gate rlz(delta) {}
  - name: rlz2
    description: Evolution under lz2
    coupling_map: []
    parameters:
    - chi
    qasm_def: gate rlz2(chi) {}
  - name: rlx
    coupling_map: []
    description: Evolution under Lx
    parameters:
    - omega
    qasm_def: gate lrx(omega) {}
  local: false
  max_experiments: 500
  max_shots: 1000
  memory: true
  n_qubits: 1
  open_pulse: false
  simulator: true
  supported_instructions:
  - rlx
  - rlz
  - rlz2
  - measure
  - barrier
  - load
