site_name: Sqooler

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow

  custom_dir: docs/overrides

nav:
  - Introduction: "index.md"
  - "General description": "description.md"
  - Contributing: contributing.md
  - Releases: releases.md
  - "Modules":
    - "Schemes": "schemes.md"
    - "Utils": "utils.md"
    - "Spoolers": "spoolers.md"
  - "Storage Providers":
    - "Basics": "storage_providers.md"
    - "MongoDB": "mongodb.md"
    - "Local storage": "local.md"
    - "Dropbox": "dropbox.md"
  - Ideas: "idea_payment.md"

repo_url: https://github.com/alqor-ug/sqooler
edit_uri: edit/main/docs/

extra:
  version:
    provider: mike
    
plugins:
- search
- mkdocstrings

markdown_extensions:
  - toc
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

