name: mkdocs 

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install requirements
      run: |
        pip install mkdocs-material
        pip install mkdocstrings
        pip install mkdocstrings[python]
    - name: Run mkdocs
      run: mkdocs gh-deploy --force